on:
 pull_request:
   types:
     - closed
     - opened
   branch: main

jobs:
  check_pr_event:
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo "The PR was merged on PROD ${{ vars.TARGET }}"
