name: bmrs_delivery_secret

on: 
  workflow_dispatch:
jobs:
  checkout_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Start of checkout action
        run: echo "Checkout process has started at :" $(date '+%d/%m/%Y %T')

      - name: Create file
        run:  |
           echo "here"
           echo $TEST_ENV_FILE>123.txt
        shell: bash
        env:
          TEST_ENV_FILE : ${{secrets.MYPAT}}

      - name: read file
        run:  |
           echo "here and trying to read 123.txt"
           #cat 123.txt

      #- name: upload file
      #  uses: actions/upload-artifact@v4
      #  with:
      #   name: my-artifact
      #   path: 123.txt
