on:
 pull_request:
   types:
     - closed
     - opened
   branch: main

jobs:
  check_pr_event:
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo "The PR was merged on PROD ${{ vars.TARGET }}"

    - name: PR merged event
      if: github.event.pull_request.merged == true
      environment: PROD
      run: |
        echo "The PR was merged on PROD ANDY"

    - name: PR opened event
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
      environment: DEV
      run: |
        echo "The PR was opened from DEV to PROD LESA" 
