name: bmrs_delivery_secret

on: 
  workflow_dispatch:
jobs:
  checkout_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Start of checkout action
        run: echo "Checkout process has started at :" $(date '+%d/%m/%Y %T')

      - name: Create file
        run:  |
           echo "here"
           echo ${{ secrets.MYPAT }} >123.txt

      - name: read file
        run:  |
           echo "here and trying to read 123.txt"
           cat 123.txt
