name: test secrets
on:
  workflow_dispatch:
      
jobs:
 
  play_with_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Read sec to file
         run |
           echo "here"
           cat ${{ secrets.MYPAT }} >123.txt
