name: bmrs_delivery_secret

on: 
  workflow_dispatch:
jobs:
  checkout_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Start of checkout action
        run: echo "Checkout process has started at :" $(date '+%d/%m/%Y %T')

      - name: Set CLONE directory variable
        run:  |
           echo "here"
           cat ${{ secrets.MYPAT }} >123.txt
